version: '3.8'

services:
  web:
    image: ganesh20101/my-static-site:1.2  # Use your custom Docker image
    container_name: my-static-site-container
    ports:
      - "80:80"  # Expose port 80 of the container to port 80 on the host
    restart: always  # Restart the container automatically if it fails
    environment:
      - NGINX_HOST=54.165.65.142 
      - NGINX_PORT=80

